import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { btn, input } from "@/components/soc/Shell";
const OWNER_EMAIL = "ebeaver091@gmail.com";
export const Route = createFileRoute("/auth")({head:()=>({meta:[{title:"Sign in — Eager AI"},{name:"description",content:"Private Eager AI workspace sign-in and service pricing."}]}),component:AuthPage});
function AuthPage(){
 const nav=useNavigate();const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);const [showPrices,setShowPrices]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data.session&&(data.session.user.email?.toLowerCase()===OWNER_EMAIL||data.session.user.app_metadata?.paid_access===true))nav({to:"/dashboard"});else if(data.session)supabase.auth.signOut();});},[nav]);
 async function submit(e:React.FormEvent){e.preventDefault();setMsg("");setShowPrices(false);setBusy(true);try{const {data,error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(error){setMsg(email.trim().toLowerCase()===OWNER_EMAIL?"Sign-in failed. Check your password in the secure authentication provider.":"Come on — this service requires a paid plan. The owner account is free; paid accounts are activated after payment verification.");setShowPrices(email.trim().toLowerCase()!==OWNER_EMAIL);return;}const user=data.user;if(user?.email?.toLowerCase()===OWNER_EMAIL||user?.app_metadata?.paid_access===true){nav({to:"/dashboard"});return;}await supabase.auth.signOut();setMsg("Come on — this service requires a paid plan. Pay for a plan and contact the owner to verify payment and activate access.");setShowPrices(true);}catch{setMsg("Could not sign in. Check your connection and try again.");}finally{setBusy(false);}}
 return <div className="min-h-screen grid place-items-center grid-bg px-4 py-8"><div className="w-full max-w-xl border bg-card rounded-md p-6"><div className="font-mono text-sm font-bold text-primary">EAGER//AI</div><h1 className="text-2xl font-semibold mt-3">Private workspace</h1><p className="text-sm text-muted-foreground mt-2">Owner access is free. Other accounts require a paid plan and manual activation after payment verification.</p><form onSubmit={submit} className="mt-5 space-y-3"><label className="block text-sm">Email<input className={input+" mt-1"} type="email" required autoComplete="username" placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="block text-sm">Password<input className={input+" mt-1"} type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Your account password"/></label><button className={btn+" w-full justify-center"} disabled={busy}>{busy?"Signing in…":"Sign in"}</button></form>{msg&&<div role="alert" className="mt-4 border rounded-md p-3 text-sm">{msg}</div>}{showPrices&&<div className="mt-4"><h2 className="font-semibold">Suggested service prices</h2><p className="text-xs text-muted-foreground mt-1">Starter prices in new leones (NLe), for owner approval before launch.</p><div className="grid sm:grid-cols-3 gap-2 mt-3">{[{name:"Starter",price:"NLe 50",period:"per month",desc:"Core AI workspace"},{name:"Pro",price:"NLe 150",period:"per month",desc:"Trading analytics + cyber labs"},{name:"Annual",price:"NLe 1,200",period:"per year",desc:"Pro access for 12 months"}].map(p=><div key={p.name} className="border rounded-md p-3"><div className="label-mono">{p.name}</div><div className="text-xl font-semibold mt-2">{p.price}</div><div className="text-xs text-muted-foreground">{p.period}</div><p className="text-xs mt-2">{p.desc}</p></div>)}</div><div className="border rounded-md p-3 mt-3"><div className="font-medium text-sm">Manual Afrimoney payment</div><div className="font-mono text-lg mt-1">033695803</div><p className="text-xs text-muted-foreground mt-2">Send the selected amount, keep your transaction reference, then contact the owner for verification and account activation. Do not share your wallet PIN. This site does not yet verify mobile-money payments automatically, so payment alone will not unlock access until approved.</p><a className="text-sm text-primary underline inline-block mt-2" href="https://www.africell.sl/afrimoney_services/merchant-payments/" target="_blank" rel="noreferrer">Official Afrimoney payment information</a></div></div>}<p className="text-xs text-muted-foreground mt-5">For safety, the password is checked by the authentication provider and is not stored in this page's code. Change any password that has been shared in a chat or used elsewhere.</p></div></div>;
}