import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Activity, Cpu, Monitor, Play, RotateCcw, Shield, Terminal, Wifi } from "lucide-react";
import { PageTitle, Panel, btn, btnGhost, input } from "@/components/soc/Shell";

export const Route = createFileRoute("/_authenticated/lab")({
  head: () => ({ meta: [{ title: "Virtual Cyber Lab — Eager AI" }, { name: "description", content: "Isolated cybersecurity learning simulations." }] }),
  component: CyberLab,
});
type Machine = { id:string; name:string; os:string; ip:string; role:string; status:"Stopped"|"Running" };
const initial: Machine[]=[
  {id:"kali",name:"Kali Linux Training",os:"Linux · simulated",ip:"192.0.2.10",role:"Security workstation",status:"Stopped"},
  {id:"target",name:"Vulnerable Web Target",os:"Linux · simulated",ip:"192.0.2.20",role:"Intentionally vulnerable training target",status:"Stopped"},
  {id:"win",name:"Windows Forensics",os:"Windows · simulated",ip:"192.0.2.30",role:"Forensic practice workstation",status:"Stopped"},
];
const help = "Available demo commands: help, clear, whoami, pwd, ls, ip addr, date, tools, nmap 192.0.2.20, wireshark demo, start <machine>, stop <machine>, reset";
function CyberLab(){
 const [machines,setMachines]=useState(initial),[active,setActive]=useState("kali"),[command,setCommand]=useState(""),[history,setHistory]=useState<string[]>(["EAGER VIRTUAL CYBER LAB v0.1","SIMULATED ENVIRONMENT — no host commands are executed.","Type help to see the available safe training commands."]),[tab,setTab]=useState<"terminal"|"packets"|"tools">("terminal");
 const current=machines.find(m=>m.id===active)!;
 const running=machines.filter(m=>m.status==="Running");
 const packets=[["10:42:01.010","192.0.2.10","192.0.2.20","TCP","SYN"],["10:42:01.018","192.0.2.20","192.0.2.10","TCP","SYN, ACK"],["10:42:01.026","192.0.2.10","192.0.2.20","TCP","ACK"],["10:42:01.044","192.0.2.10","192.0.2.20","HTTP","GET /training"],["10:42:01.061","192.0.2.20","192.0.2.10","HTTP","200 OK"]];
 function run(raw:string){const c=raw.trim();if(!c)return;const parts=c.toLowerCase().split(/\s+/);let output="";
  if(parts[0]==="help")output=help;
  else if(parts[0]==="clear"){setHistory(["Terminal cleared. SIMULATED LAB DATA"]);setCommand("");return;}
  else if(parts[0]==="whoami")output="student@eager-lab (simulated)";
  else if(parts[0]==="pwd")output="/home/student";
  else if(parts[0]==="ls")output="Desktop  Documents  captures/  reports/  sample.pcap";
  else if(parts[0]==="date")output=new Date().toUTCString()+" (client clock)";
  else if(parts[0]==="ip"&&parts[1]==="addr")output=`lo: 127.0.0.1/8\neth0: ${current.ip}/24 (SIMULATED)`;
  else if(parts[0]==="tools")output="Wireshark (packet viewer demo) · Nmap (allowlisted lab simulation) · SHA-256 · HTTP inspector · Log viewer";
  else if(parts[0]==="nmap"){if(parts[1]!=="192.0.2.20")output="Blocked: only the designated documentation-range training target 192.0.2.20 is allowed in this simulator.";else output="SIMULATED Nmap scan report for 192.0.2.20\nHost is up (0.001s simulated latency).\nPORT   STATE SERVICE\n22/tcp open  ssh (training fixture)\n80/tcp open  http (intentionally vulnerable lab fixture)\nNo network packets were sent.";
  }else if(parts[0]==="wireshark"&&parts[1]==="demo"){setTab("packets");output="Opened sample packet capture in the Wireshark-style packet viewer. These packets are fabricated training fixtures.";
  }else if(parts[0]==="start"){const m=machines.find(x=>x.id===parts.slice(1).join("-")||x.id===parts[1]);if(!m)output="Machine not found. Use the machine list to select a lab.";else{setMachines(prev=>prev.map(x=>x.id===m.id?{...x,status:"Running"}:x));output=`${m.name} started in simulated mode. No real virtual machine was provisioned.`;}}
  else if(parts[0]==="stop"){const id=parts[1];setMachines(prev=>prev.map(x=>x.id===id?{...x,status:"Stopped"}:x));output=`Stop requested for ${id||"selected machine"} (simulator state only).`;}
  else if(parts[0]==="reset"){setMachines(initial);setActive("kali");output="Lab state reset."; }
  else output=`Command not available in the safe simulator: ${c}\nThis terminal does not execute operating-system commands. Type help.`;
  setHistory(prev=>[...prev,`student@eager-lab:~$ ${c}`,output]);setCommand("");
 }
 const commandCount=useMemo(()=>history.filter(x=>x.includes("student@eager-lab:~$")).length,[history]);
 return <><PageTitle code="LAB-01 // ISOLATED TRAINING" title="Virtual Cyber Lab"><span className="font-mono text-xs text-muted-foreground">{running.length} simulated machines active</span></PageTitle>
 <div className="mb-4 rounded-md border border-warning/40 bg-warning/5 p-3 text-sm"><strong>Prototype lab:</strong> machines and terminal responses on this page are simulated; no real VM is provisioned yet. Real Kali/Windows desktops, shell access, packet capture and Wireshark require a separate isolated VM host (such as Kasm Workspaces or Apache Guacamole connected to disposable VMs), authentication, network egress restrictions and server-side provisioning.</div>
 <div className="grid gap-4 xl:grid-cols-[290px_minmax(0,1fr)]">
 <div className="space-y-4"><Panel title="Lab machines" action={<span className="label-mono">3 FIXTURES</span>}><div className="space-y-2">{machines.map(m=><button key={m.id} onClick={()=>setActive(m.id)} className={`w-full text-left border rounded-md p-3 ${active===m.id?"border-primary bg-accent/40":"hover:bg-secondary"}`}><div className="flex items-center gap-2"><Monitor size={17}/><span className="font-medium text-sm">{m.name}</span><span className={`ml-auto size-2 rounded-full ${m.status==="Running"?"bg-success":"bg-muted-foreground"}`}/></div><div className="text-xs text-muted-foreground mt-2">{m.os} · {m.ip}</div><div className="text-xs mt-1">{m.role}</div><div className="flex gap-2 mt-3"><span className="label-mono">{m.status.toUpperCase()}</span></div></button>)}</div><div className="grid grid-cols-2 gap-2 mt-3"><button className={btn+" justify-center"} onClick={()=>setMachines(p=>p.map(m=>m.id===active?{...m,status:"Running"}:m))}><Play size={14}/> Start demo</button><button className={btnGhost+" justify-center"} onClick={()=>setMachines(p=>p.map(m=>m.id===active?{...m,status:"Stopped"}:m))}>Stop demo</button></div><p className="text-xs text-muted-foreground mt-2">These controls change only the local demo state.</p></Panel>
 <Panel title="Lab safety"><div className="space-y-3 text-sm"><div className="flex gap-2"><Shield size={17} className="text-primary shrink-0"/><span>Isolated training fixtures and reserved documentation IP range.</span></div><div className="flex gap-2"><Wifi size={17} className="text-primary shrink-0"/><span>No outbound scanning or access to real targets.</span></div><div className="flex gap-2"><Cpu size={17} className="text-primary shrink-0"/><span>Unknown malware is never executed here.</span></div></div></Panel></div>
 <div className="min-w-0 space-y-4"><Panel title={`Workspace · ${current.name}`} action={<div className="flex gap-1"><button className={tab==="terminal"?btn:btnGhost} onClick={()=>setTab("terminal")}><Terminal size={13}/> Terminal</button><button className={tab==="packets"?btn:btnGhost} onClick={()=>setTab("packets")}>Wireshark</button><button className={tab==="tools"?btn:btnGhost} onClick={()=>setTab("tools")}>Tools</button></div>}>
 {tab==="terminal"&&<><div className="bg-[#0b1110] text-green-300 font-mono text-xs p-4 rounded-md min-h-[310px] max-h-[460px] overflow-auto whitespace-pre-wrap">{history.map((line,i)=><div key={i} className={line.startsWith("student@")?"text-green-200 mb-1":"mb-3"}>{line}</div>)}</div><form className="flex gap-2 mt-3" onSubmit={e=>{e.preventDefault();run(command);}}><span className="font-mono text-xs self-center text-muted-foreground">lab$</span><input className={input+" font-mono"} aria-label="Lab demo command" placeholder="Type help…" value={command} onChange={e=>setCommand(e.target.value)}/><button className={btn} type="submit">Run</button></form><div className="flex flex-wrap gap-2 mt-3">{["help","ls","ip addr","tools","nmap 192.0.2.20","wireshark demo"].map(c=><button key={c} className={btnGhost} onClick={()=>run(c)}>{c}</button>)}</div></>}
 {tab==="packets"&&<><div className="flex items-center gap-2 mb-3 text-sm"><Activity size={17} className="text-primary"/> Sample capture · SIMULATED LAB DATA <button className={btnGhost+" ml-auto"} onClick={()=>setHistory(p=>[...p,"Loaded sample packet capture. No interface capture performed."])}>Log to terminal</button></div><div className="overflow-x-auto"><table className="w-full text-xs font-mono"><thead><tr className="text-left border-b text-muted-foreground">{["Time","Source","Destination","Protocol","Info"].map(h=><th key={h} className="py-2 pr-3">{h}</th>)}</tr></thead><tbody>{packets.map((p,i)=><tr key={i} className="border-b"><td className="py-2 pr-3">{p[0]}</td><td className="pr-3">{p[1]}</td><td className="pr-3">{p[2]}</td><td className="pr-3 text-primary">{p[3]}</td><td>{p[4]}</td></tr>)}</tbody></table></div><p className="text-xs text-muted-foreground mt-3">Wireshark-style preview only. To inspect real traffic, install Wireshark on an authorized host or connect this interface to a separately deployed isolated lab capture service.</p></>}
 {tab==="tools"&&<div className="grid sm:grid-cols-2 gap-3">{[{name:"Wireshark packet viewer",desc:"Inspect sample Ethernet/IP/TCP/HTTP frames.",action:()=>setTab("packets")},{name:"Nmap lab scan",desc:"Simulated service discovery against the designated fixture.",action:()=>{setTab("terminal");run("nmap 192.0.2.20");}},{name:"File hash inspector",desc:"Calculate SHA-256 in the Security Operations workspace.",action:()=>window.location.assign("/security")},{name:"Incident response",desc:"Record authorized cases and analyst findings.",action:()=>window.location.assign("/cases")}].map(t=><button key={t.name} className="border rounded-md p-4 text-left hover:bg-secondary" onClick={t.action}><div className="font-medium text-sm">{t.name}</div><div className="text-xs text-muted-foreground mt-2">{t.desc}</div><div className="label-mono mt-3 text-primary">OPEN TOOL →</div></button>)}</div>}
 </Panel><div className="grid sm:grid-cols-3 gap-3">{[{label:"Commands run",value:commandCount},{label:"Machines running",value:running.length},{label:"Environment",value:"SIMULATED"}].map(s=><div key={s.label} className="border bg-card rounded-md p-3"><div className="label-mono">{s.label}</div><div className="font-mono text-lg mt-1">{s.value}</div></div>)}</div><button className={btnGhost} onClick={()=>{setMachines(initial);setHistory(["EAGER VIRTUAL CYBER LAB v0.1","SIMULATED ENVIRONMENT — no host commands are executed.","Type help to see the available safe training commands."]);setTab("terminal");setCommand("");}}><RotateCcw size={14}/> Reset demo</button></div></div></>;
}
