import { createFileRoute } from "@tanstack/react-router";
import { useRef, useState } from "react";
import { PageTitle, Panel, btn, btnGhost, input } from "@/components/soc/Shell";
export const Route = createFileRoute("/_authenticated/trading")({ head:()=>({meta:[{title:"Trading Intelligence — Eager AI"}]}), component: TradingPage });
type Trade={date:string;symbol:string;side:string;pnl:number};
function TradingPage(){
 const ref=useRef<HTMLInputElement>(null); const [rows,setRows]=useState<Trade[]>([]); const [notice,setNotice]=useState("");
 async function load(file?:File){if(!file)return;try{const lines=(await file.text()).replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);if(lines.length<2)throw Error("CSV needs a header and at least one row.");const split=(s:string)=>s.split(",").map(x=>x.trim().replace(/^"|"$/g,""));const h=split(lines[0]).map(x=>x.toLowerCase().replace(/[^a-z]/g,""));const si=h.findIndex(x=>["symbol","instrument","asset","pair","ticker"].includes(x));const pi=h.findIndex(x=>["pnl","profit","netprofit","realizedpnl","profitloss"].includes(x));const di=h.findIndex(x=>["date","closedat","closetime","time"].includes(x));const ti=h.findIndex(x=>["side","type","direction","action"].includes(x));if(si<0||pi<0)throw Error("CSV must contain Symbol/Instrument and PnL/Profit columns.");const parsed=lines.slice(1).map(line=>{const c=split(line);return {date:di<0?"—":c[di]||"—",symbol:c[si]||"Unknown",side:ti<0?"—":c[ti]||"—",pnl:Number((c[pi]||"0").replace(/[$,]/g,""))};}).filter(t=>t.symbol!=="Unknown"&&Number.isFinite(t.pnl));if(!parsed.length)throw Error("No valid trades found.");setRows(parsed);setNotice(`Loaded ${parsed.length} trades locally. The CSV was not uploaded.`);}catch(e){setNotice(e instanceof Error?e.message:"Unable to read CSV.");}}
 const total=rows.reduce((s,t)=>s+t.pnl,0),wins=rows.filter(t=>t.pnl>0).length,losses=rows.filter(t=>t.pnl<0).length;const fmt=(n:number)=>new Intl.NumberFormat("en-SL",{style:"currency",currency:"SLE",maximumFractionDigits:2}).format(n);
 return <><PageTitle code="TRD-01 // PRIVATE ANALYTICS" title="Trading Intelligence"/><div className="mb-4 rounded-md border border-warning/40 bg-warning/5 p-3 text-sm"><strong>Read-only mode.</strong> Direct broker connections are not configured yet. Never enter broker passwords, seed phrases, or withdrawal-enabled API keys here. Import a broker-exported CSV to analyze history.</div><div className="grid md:grid-cols-2 gap-4 mb-4"><Panel title="Import trades"><p className="text-sm text-muted-foreground">CSV columns supported: Symbol/Instrument, PnL/Profit; Date and Side are optional.</p><input ref={ref} className="hidden" type="file" accept=".csv,text/csv" onChange={e=>load(e.target.files?.[0])}/><button className={btn+" mt-3"} onClick={()=>ref.current?.click()}>Choose trade CSV</button><button className={btnGhost+" mt-3 ml-2"} onClick={()=>{setRows([{date:"Sample",symbol:"EURUSD",side:"Long",pnl:36},{date:"Sample",symbol:"XAUUSD",side:"Short",pnl:26},{date:"Sample",symbol:"GBPUSD",side:"Long",pnl:-35}]);setNotice("Sample values only — not real trading data.");}}>Load sample</button><p role="status" className="text-sm mt-3">{notice}</p></Panel><Panel title="Account connection"><div className="text-sm">Provider connection status: <strong>Not configured</strong></div><p className="text-xs text-muted-foreground mt-2">A supported broker aggregator such as SnapTrade needs server-side API credentials, account linking and callback configuration before a live read-only connection can be enabled.</p></Panel></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-4">{[{k:"Net P/L",v:rows.length?fmt(total):"—"},{k:"Trades",v:rows.length},{k:"Winners",v:rows.length?wins:"—"},{k:"Losers",v:rows.length?losses:"—"}].map(s=><div key={s.k} className="border bg-card rounded-md p-4"><div className="label-mono">{s.k}</div><div className="font-mono text-xl mt-2">{s.v}</div></div>)}</div><Panel title={`Trade ledger · ${rows.length} trades`}>{rows.length?<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-muted-foreground">{["Date","Symbol","Side","P/L"].map(h=><th key={h} className="py-2 pr-4">{h}</th>)}</tr></thead><tbody>{rows.map((t,i)=><tr key={i} className="border-b"><td className="py-2 pr-4">{t.date}</td><td className="pr-4 font-mono">{t.symbol}</td><td className="pr-4">{t.side}</td><td className={t.pnl>=0?"text-success":"text-destructive"}>{fmt(t.pnl)}</td></tr>)}</tbody></table></div>:<p className="text-sm text-muted-foreground py-5">Import your own CSV to start. Imported data remains in this browser session only.</p>}<p className="text-xs text-muted-foreground mt-3">Past performance does not predict future results. Currency and profit calculations depend on your broker's export format and fees.</p></Panel></>;
}